apiVersion: apps/v1
kind: Deployment
metadata:
  name: techie-d
  labels:
    app: techie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techie
  template:
    metadata:
      labels:
        app: techie
    spec:
      imagePullSecrets:
      - name: regcrednheek
      containers:
      - name: techie
        image: reg.nheek.com/nheek/techie:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "40Mi"
          limits:
            memory: "70Mi"
