apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techie-hpa
  namespace: static
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techie-d
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
